import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFile } from "fs/promises";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Plugin to combine Monaco CSS with our custom CSS
let cssPlugin = {
	name: 'combine-css',
	setup(build) {
		build.onEnd(result => {
			try {
				// Read Monaco's generated CSS
				const monacoCSS = fs.readFileSync('main.css', 'utf8');
				// Backup our custom styles first
				const customCSS = fs.readFileSync('styles.css', 'utf8');
				// Combine them
				const combinedCSS = monacoCSS + '\n' + customCSS;
				// Write back to styles.css (this is what Obsidian loads)
				fs.writeFileSync('styles.css', combinedCSS, 'utf8');
				console.log('✓ Combined Monaco CSS with custom styles');
			} catch (err) {
				console.log('Note: No Monaco CSS to combine:', err.message);
			}
		});
	},
};

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		".ttf": "base64",
		".css": "css",
	},
	plugins: [cssPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
